# Generated by Django 2.2.7 on 2019-11-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='thumbnail',
        ),
    ]
